version: "3.3"
services:

  db:
    image: "postgres:14.0-alpine"
    environment:
      POSTGRES_DB: zebrands_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: zebrands123
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=root --dbname=zebrands_db"]
      interval: 5s
      timeout: 5s
      retries: 5